### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by ihancock**

### CODE REVIEW

**Comment by denisviana** [comment]
Seems this package is abandoned

**Comment by bismarabia** [comment]
Any news regarding this? when are you planning to migrate to null-safety? @infitio

**Comment by tiholic** [comment]
@ihancock that PR is landed. It would be great if you can rebase and publish new changes

**Comment by ihancock** [comment]
Sure I will take a look.

Regards
Ian

**Comment by nerdsarena** [comment]
any updates ?!

**Pull request closed without merging**
